from __future__ import annotations

from phishintel.models import AnalysisReport, Verdict

VERDICT_COLORS = {
    Verdict.MALICIOUS: "red",
    Verdict.SUSPICIOUS: "orange",
    Verdict.BENIGN: "green",
    Verdict.INCONCLUSIVE: "gray",
}


def wiki_comment(report: AnalysisReport) -> str:
    color = VERDICT_COLORS.get(report.verdict, "gray")
    lines = [
        "h2. PhishIntel analysis",
        f"*Verdict:* {{color:{color}}}*{report.verdict.value.upper()}*{{color}} "
        f"({int(report.confidence * 100)}% · {report.verdict_source})",
        "",
        "h3. Summary",
        report.summary or "_No summary_",
        "",
        "h3. Sender",
        "|| Field || Value ||",
        f"| From | {report.sender.from_addr.display_name} <{report.sender.from_addr.address}> |",
        f"| Return-Path | {report.sender.return_path.address or '_n/a_'} |",
        f"| Reply-To | {report.sender.reply_to.address or '_n/a_'} |",
        f"| SPF / DKIM / DMARC | {report.sender.auth.spf or '?'} / "
        f"{report.sender.auth.dkim or '?'} / {report.sender.auth.dmarc or '?'} |",
        f"| Originating IP | {report.sender.originating_ip or '_n/a_'} |",
        f"| Spoof signals | {', '.join(report.sender.spoof_signals) or '_none_'} |",
        f"| Lookalikes | {_lookalikes(report)} |",
        "",
        "h3. URLs",
    ]
    if report.urls:
        lines.append("|| Original / rewritten || Decoded destination || Domain || Rewriter || Display mismatch ||")
        for url in report.urls:
            original = _short(url.original)
            decoded = _short(url.final if url.final != url.original else (url.decoded or "_same_"))
            lines.append(
                f"| {original} | {decoded} | {url.domain or ''} | "
                f"{url.rewriter or '_none_'} | {'YES' if url.display_mismatch else 'no'} |"
            )
    else:
        lines.append("_No URLs extracted_")

    lines.extend(["", "h3. Threat intel"])
    if report.intel:
        lines.append("|| Provider || Target || Verdict || Detections || Link ||")
        for item in report.intel:
            link = f"[open|{item.permalink}]" if item.permalink else "_n/a_"
            detections = f"{item.malicious}M / {item.suspicious}S"
            lines.append(
                f"| {item.provider} | {_short(item.target)} | *{item.verdict}* | {detections} | {link} |"
            )
    else:
        lines.append("_No VirusTotal / urlscan / Mimecast intel (check API keys)_")

    if report.email.attachments:
        lines.extend(["", "h3. Attachments", "|| Name || Type || SHA256 || Dangerous ||"])
        for att in report.email.attachments:
            lines.append(
                f"| {att.filename} | {att.content_type} | {att.sha256} | "
                f"{'YES' if att.dangerous else 'no'} |"
            )

    lines.extend(["", "h3. Why this verdict"])
    if report.rationale:
        lines.extend(f"* {item}" for item in report.rationale)
    else:
        lines.append("_n/a_")

    lines.extend(["", "h3. Recommended actions"])
    lines.extend(f"# {item}" for item in report.recommended_actions)

    if report.iocs:
        lines.extend(["", "h3. IOCs", "{code}"])
        lines.extend(report.iocs)
        lines.append("{code}")

    if report.errors:
        lines.extend(["", "h3. Analyzer notes"])
        lines.extend(f"* {err}" for err in report.errors)

    lines.extend(
        [
            "",
            "----",
            "_Generated by PhishIntel. Do not click decoded URLs from an unmanaged browser._",
            "<!-- phishintel:v1 -->",
        ]
    )
    return "\n".join(lines)


def _lookalikes(report: AnalysisReport) -> str:
    if not report.sender.lookalikes:
        return "_none_"
    return ", ".join(f"{h.candidate} ~ {h.target} ({h.kind})" for h in report.sender.lookalikes)


def _short(value: str, limit: int = 90) -> str:
    value = value.replace("|", "\\|")
    if len(value) <= limit:
        return value
    return value[: limit - 3] + "..."
